#!/bin/sh
Fatal() {
	echo "$*" >&2
	exit 1
}
[ $# -eq 1 ] || Fatal "Usage: ${0##*/} [binary]"
cmd=$1
Test() {
	echo "$cmd $*"
	result=`"$cmd" "$@"` || Fatal 'execution failed'
	echo "$result"
}
Check() {
	[ "$result" = "$*" ] || Fatal "result but should be $*"
}
Test -e 1 8
Check '0'
Test 1 8
Check '0'
Test -e 7 1 3 5
Check '6
1 5'
Test -e 6 9 1 3 5 8
Check '6
1 5'
Test 9 1 1.5 1 2.5 1 2 8
Check '10.5
1(2.5) 8(8)'
Test -eu 7 8 1 9
Check '7
7*1=7'
Test -eu 11 3 5 7
Check '11
2*3=6 1*5=5'
Test -u 14 3 3.5 5 7.5 7
Check '18.5
1*3(1*3.5=3.5) 2*5(2*7.5=15)'
